export { actions, reducer } from './cv.slice'
export { actions as evaluatedPointsActions, reducer as evaluatedPointsReducer } from './evaluated-points.slice'
export { actions as contactsActions, reducer as contactsReducer } from './contacts-with-icon.slice'
export { actions as linksActions, reducer as linksReducer } from './links-contacts.slice'
export type { EvaluatedPoint } from './evaluated-points.slice'
export { actions as extendedTextActions, reducer as extendedTextReducer } from './extended-text.slice'